# Generated by Django 5.0.3 on 2024-03-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
